/// Flutter icons BarkMeet
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BarkMeet
///      fonts:
///       - asset: fonts/BarkMeet.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
library;
import 'package:flutter/widgets.dart';

class BarkMeet {
  BarkMeet._();

  static const _kFontFam = 'BarkMeet';
  static const String? _kFontPkg = null;

  static const IconData person_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supp = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_f = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog_circle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData points = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
