// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrZgHZAyoV82YrxRvThzt1hJCE4tJe1CY',
    appId: '1:469541800643:web:3536cd30fe6d8441897076',
    messagingSenderId: '469541800643',
    projectId: 'barkandmeet',
    authDomain: 'barkandmeet.firebaseapp.com',
    storageBucket: 'barkandmeet.appspot.com',
    measurementId: 'G-YX6L4JD4N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ8qZJeJPXxe4uuA0XMkZsp7U-YDoKItE',
    appId: '1:469541800643:android:f65d8814fbc802c4897076',
    messagingSenderId: '469541800643',
    projectId: 'barkandmeet',
    storageBucket: 'barkandmeet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC-DsyfF2DLMtVxSKXhrUtkiVllrJnhwc',
    appId: '1:469541800643:ios:4f18bc60633b56ea897076',
    messagingSenderId: '469541800643',
    projectId: 'barkandmeet',
    storageBucket: 'barkandmeet.appspot.com',
    iosBundleId: 'com.example.barkAndMeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC-DsyfF2DLMtVxSKXhrUtkiVllrJnhwc',
    appId: '1:469541800643:ios:4f18bc60633b56ea897076',
    messagingSenderId: '469541800643',
    projectId: 'barkandmeet',
    storageBucket: 'barkandmeet.appspot.com',
    iosBundleId: 'com.example.barkAndMeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrZgHZAyoV82YrxRvThzt1hJCE4tJe1CY',
    appId: '1:469541800643:web:be9bebf1fecfc972897076',
    messagingSenderId: '469541800643',
    projectId: 'barkandmeet',
    authDomain: 'barkandmeet.firebaseapp.com',
    storageBucket: 'barkandmeet.appspot.com',
    measurementId: 'G-7ZSKJCDQXD',
  );
}
